services:
  searxng:
    image: searxng/searxng:2026.5.10-df1f24fb7
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - "SEARXNG_BASE_URL=http://localhost:8080"
    restart: unless-stopped
