"""SearXNG Python SDK."""

from .searxng_search import (
    SearXNG,
    SearXNGBaseConfiguration,
    SearXNGSearchConfiguration,
    Category,
    TimeRange,
    Autocomplete,
    SafeSearch,
    Theme,
    Plugins,
    SearXNGResponse,
    GeneralOrNewsResult,
    ImageResult,
    VideoResult,
    MapResult,
    ITResult,
    ScienceResult,
    MusicResult,
    FileResult,
    SocialMediaResult,
)

__all__ = [
    "SearXNG",
    "SearXNGBaseConfiguration",
    "SearXNGSearchConfiguration",
    "Category",
    "TimeRange",
    "Autocomplete",
    "SafeSearch",
    "Theme",
    "Plugins",
    "SearXNGResponse",
    "GeneralOrNewsResult",
    "ImageResult",
    "VideoResult",
    "MapResult",
    "ITResult",
    "ScienceResult",
    "MusicResult",
    "FileResult",
    "SocialMediaResult",
]
